### ISSUE TITLE
Problem with react 18

### ISSUE THREAD

**Issue by dara1400** [GR34SE/react-switch-selector#155]
Hello

I got this error when I am using it in react 18:

Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (http://localhost:3000/static/js/bundle.js:35084:17)
    at useState (http://localhost:3000/static/js/bundle.js:35110:24)
    at __WEBPACK_DEFAULT_EXPORT__ (http://localhost:3000/static/js/bundle.js:43535:61)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:21478:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:24764:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:26060:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:11070:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:11114:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:11171:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:31045:11)

**Comment by peterzanetti** [comment]
Any update here? Just not going to work with React 18?

**Comment by GR34SE** [comment]
Please try with https://github.com/GR34SE/react-switch-selector/releases/tag/v2.3.0
